name: Python CI

on:
  push:
  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Show Python & pip versions
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Create junit directory
        run: mkdir -p junit

      - name: Run tests with coverage
        run: |
          pytest my_package/tests \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=my_package \
            --cov-report=xml \
            --cov-report=html
